// This file is auto generated by src/help_gen.pl
// do not edit this file.
package runtime;
class Help {
	public static void show() {
		System.out.println(""
			+"    -x <name> <value>\n"
			+"                    User defined option.\n"
			+"                    <name>    <value>    description\n"
			+"                    =================================================================\n"
			+"                    screen    max        full screen mode\n"
			+"                    auto      on         reaction auto proceed mode when GUI enabled\n"
			+"    -L <path>\n"
			+"                    Additional path for classpath (inline code compile time)\n"
			+"    -I <path>\n"
			+"                    Additional path for LMNtal library\n"
			+"                    default path is ./lmntal_lib and ../lmntal_lib\n"
			+"    -cgi\n"
			+"                    CGI mode. Output header 'Content-type:text/html'\n"
			+"    -d<0-9>\n"
			+"                    Debug level.\n"
			+"    -v<0-9>\n"
			+"                    Verbose output level.\n"
			+"    -g\n"
			+"                    GUI mode. Atoms, Membranes, Links are drawn.\n"
			+"                    A reaction proceeds after button click.\n"
			+"    -t\n"
			+"                    Trace mode.\n"
			+"    -s<0-9>\n"
			+"                    Shuffle level. Random application of reaction rules.\n"
			+"    -e <LMNtal program>\n"
			+"                    One liner code execution like perl.\n"
			+"                    Example: -e 'a,(a:-b)'\n"
			+"    -O<0-9>\n"
			+"                    Optimize level.\n"
			+"    --help\n"
			+"                    Show usage(this).\n"
			+"    --demo\n"
			+"                    Demo mode. Atoms and strings will be drawn larger.\n"
		);
	}
}
