/* The following code was generated by JFlex 1.4.1 on 06/06/20 16:33 */

/**
	This is LMNtal Lex file.
*/

/* --------------------------Usercode Section------------------------ */
package compile.parser;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 06/06/20 16:33 from the specification file
 * <tt>lmntal.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int QUOTED = 1;
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 3;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\2\1\0\1\3\1\1\22\0\1\11\1\22\1\17"+
    "\1\16\1\46\1\31\1\0\1\20\1\34\1\35\1\32\1\15\1\33"+
    "\1\42\1\13\1\30\12\12\1\24\1\0\1\26\1\21\1\27\1\25"+
    "\1\40\2\4\1\4\1\4\1\14\25\4\1\47\1\23\1\50\1\44"+
    "\1\41\1\0\1\5\1\5\1\5\1\53\1\10\1\55\1\5\1\5"+
    "\4\5\1\51\1\54\1\52\2\5\1\6\1\5\1\7\6\5\1\36"+
    "\1\43\1\37\1\45\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\2\3\1\4\2\5\1\6\1\7"+
    "\1\3\1\10\1\2\1\11\2\2\1\12\3\11\1\13"+
    "\1\3\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\5"+
    "\3\32\1\33\1\32\3\1\3\0\1\34\1\35\1\3"+
    "\3\0\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\5\1\53"+
    "\1\0\1\54\1\55\1\56\1\57\1\60\1\61\1\1"+
    "\1\62\1\1\1\63\1\34\1\0\3\3\1\64\1\65"+
    "\1\66\1\67\1\70\2\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\270\0\u0114"+
    "\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\270\0\u0228\0\u0256"+
    "\0\u0284\0\u02b2\0\u02e0\0\270\0\u030e\0\u033c\0\u036a\0\u0398"+
    "\0\u03c6\0\270\0\270\0\270\0\270\0\u03f4\0\u0422\0\u0450"+
    "\0\270\0\270\0\270\0\270\0\u047e\0\270\0\u04ac\0\270"+
    "\0\u04da\0\u0508\0\270\0\u0536\0\u0564\0\270\0\u0592\0\u05c0"+
    "\0\u05ee\0\u019e\0\u061c\0\270\0\u064a\0\u0678\0\u06a6\0\u06d4"+
    "\0\270\0\270\0\270\0\270\0\270\0\270\0\u0702\0\270"+
    "\0\270\0\u0730\0\270\0\270\0\270\0\u075e\0\270\0\346"+
    "\0\270\0\270\0\270\0\270\0\270\0\270\0\u078c\0\270"+
    "\0\u07ba\0\u07e8\0\u0816\0\u0816\0\u0844\0\u0872\0\u08a0\0\u06a6"+
    "\0\270\0\u08ce\0\270\0\u0142\0\u0398\0\270\0\270";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\2\7\1\10\4\11\1\7\1\12\1\13"+
    "\1\10\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\10\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\4\11\1\50"+
    "\1\51\22\50\1\52\32\50\1\6\2\7\13\50\1\53"+
    "\3\50\1\54\32\50\2\55\1\56\27\55\1\57\23\55"+
    "\60\0\1\7\57\0\5\10\1\0\1\10\1\0\1\10"+
    "\24\0\1\10\7\0\5\10\4\0\5\11\1\0\1\11"+
    "\1\60\1\11\24\0\1\11\7\0\5\11\10\0\1\61"+
    "\1\0\1\12\1\62\1\61\53\0\1\63\56\0\1\64"+
    "\42\0\1\30\1\6\2\7\13\30\1\65\36\30\1\66"+
    "\2\0\15\66\1\67\35\66\21\0\1\24\1\0\2\70"+
    "\1\0\1\25\50\0\1\24\51\0\1\71\3\0\1\24"+
    "\60\0\1\24\15\0\1\72\26\0\1\24\55\0\1\24"+
    "\5\0\1\25\47\0\1\73\14\0\1\30\1\0\1\74"+
    "\23\0\1\30\1\6\2\7\52\30\13\0\1\75\16\0"+
    "\1\76\53\0\1\77\1\0\1\100\5\0\1\101\1\102"+
    "\54\0\1\103\30\0\1\104\66\0\1\105\35\0\5\11"+
    "\1\0\1\11\1\60\1\11\24\0\1\11\7\0\1\11"+
    "\1\106\3\11\2\0\1\50\123\0\1\107\6\0\1\110"+
    "\1\7\3\0\1\111\1\112\7\0\1\113\3\0\1\114"+
    "\30\0\1\115\1\116\2\55\1\56\27\55\1\0\23\55"+
    "\2\117\1\56\25\117\1\120\1\117\1\121\23\117\5\0"+
    "\4\122\1\0\1\122\36\0\5\122\12\0\1\123\2\0"+
    "\1\124\24\0\1\124\23\0\1\61\1\0\1\63\1\0"+
    "\1\61\41\0\1\125\1\126\1\7\1\127\52\125\1\66"+
    "\2\0\15\66\1\130\35\66\20\0\1\66\56\0\1\25"+
    "\74\0\1\131\45\0\1\132\7\0\1\133\21\0\5\11"+
    "\1\0\1\11\1\60\1\11\24\0\1\11\7\0\2\11"+
    "\1\134\2\11\2\117\1\56\25\117\1\0\1\117\1\0"+
    "\25\117\1\56\25\117\1\0\1\117\1\121\23\117\4\0"+
    "\5\122\1\0\1\122\1\0\1\122\24\0\1\122\7\0"+
    "\5\122\12\0\1\123\43\0\1\30\1\6\2\7\13\30"+
    "\1\135\36\30\2\0\1\7\14\0\1\136\55\0\1\136"+
    "\76\0\1\137\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2300];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\1\1\11\1\1\1\11\6\1\1\11\5\1"+
    "\1\11\5\1\4\11\3\1\4\11\1\1\1\11\1\1"+
    "\1\11\2\1\1\11\2\1\1\11\1\1\3\0\1\1"+
    "\1\11\1\1\3\0\6\11\1\1\2\11\1\1\3\11"+
    "\1\1\1\11\1\0\6\11\1\1\1\11\3\1\1\0"+
    "\4\1\1\11\1\1\1\11\2\1\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private final boolean _DEBUG = true;
	StringBuffer string = new StringBuffer();
	StringBuffer token = new StringBuffer();
	int startline, startcol;

    private Symbol symbol(int type) {
    	return symbol(type, null, yytext(), yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) {
    	return symbol(type, value, yytext(), yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value, String token) {
    	return symbol(type, value, token, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value, String token, int line, int col) {
        return new MySymbol(token, type, line+1, col+1, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return symbol(sym.GUARD);
          }
        case 59: break;
        case 57: 
          { return symbol(sym.CHAR_CODE_LITERAL,	yytext());
          }
        case 60: break;
        case 41: 
          { return symbol(sym.MINUS_DOT);
          }
        case 61: break;
        case 39: 
          { return symbol(sym.RBRACE_UNDERBAR);
          }
        case 62: break;
        case 15: 
          { return symbol(sym.RPAREN);
          }
        case 63: break;
        case 48: 
          { token.append(yytext()); string.append("\n");
          }
        case 64: break;
        case 29: 
          { return symbol(sym.PLUS_DOT);
          }
        case 65: break;
        case 30: 
          { return symbol(sym.NEGATIVE);
          }
        case 66: break;
        case 21: 
          { return symbol(sym.HAT);
          }
        case 67: break;
        case 16: 
          { return symbol(sym.LBRACE);
          }
        case 68: break;
        case 42: 
          { string.setLength(0); token.setLength(0); token.append(yytext()); startline = yyline; startcol = yycolumn; yybegin(QUOTED);
          }
        case 69: break;
        case 24: 
          { return symbol(sym.LBRACKET);
          }
        case 70: break;
        case 53: 
          { return symbol(sym.RBRACE_SLASH_AT);
          }
        case 71: break;
        case 23: 
          { return symbol(sym.PROCVAR);
          }
        case 72: break;
        case 8: 
          { string.setLength(0); token.setLength(0); token.append(yytext()); startline = yyline; startcol = yycolumn; yybegin(STRING);
          }
        case 73: break;
        case 43: 
          { token.append(yytext()); yybegin(YYINITIAL); return symbol(sym.QUOTED_STRING, string.toString(), token.toString(), startline, startcol);
          }
        case 74: break;
        case 38: 
          { return symbol(sym.RBRACE_AT);
          }
        case 75: break;
        case 52: 
          { return symbol(sym.SYMBOL_NAME,		yytext());
          }
        case 76: break;
        case 11: 
          { return symbol(sym.SLASH);
          }
        case 77: break;
        case 50: 
          { yybegin(YYINITIAL);
          }
        case 78: break;
        case 18: 
          { return symbol(sym.RULEVAR);
          }
        case 79: break;
        case 7: 
          { return symbol(sym.PLUS);
          }
        case 80: break;
        case 56: 
          { return symbol(sym.MOD);
          }
        case 81: break;
        case 6: 
          { return symbol(sym.PERIOD);
          }
        case 82: break;
        case 36: 
          { return symbol(sym.RBRACE_SLASH);
          }
        case 83: break;
        case 58: 
          { return symbol(sym.RBRACE_UNDERBAR_SLASH_AT);
          }
        case 84: break;
        case 12: 
          { return symbol(sym.ASTERISK);
          }
        case 85: break;
        case 51: 
          { return symbol(sym.PATHED_ATOM_NAME,	yytext());
          }
        case 86: break;
        case 33: 
          { yybegin(COMMENT);
          }
        case 87: break;
        case 4: 
          { return symbol(sym.LINK_NAME,			yytext(), yytext(), yyline, yycolumn);
          }
        case 88: break;
        case 25: 
          { return symbol(sym.RBRACKET);
          }
        case 89: break;
        case 10: 
          { return symbol(sym.COLON);
          }
        case 90: break;
        case 45: 
          { token.append(yytext()); string.append("\t");
          }
        case 91: break;
        case 34: 
          { return symbol(sym.ASTERISK_DOT);
          }
        case 92: break;
        case 32: 
          { return symbol(sym.SLASH_DOT);
          }
        case 93: break;
        case 35: 
          { return symbol(sym.ASTERISK_ASTERISK);
          }
        case 94: break;
        case 37: 
          { return symbol(sym.RBRACE_ASTERISK);
          }
        case 95: break;
        case 14: 
          { return symbol(sym.LPAREN);
          }
        case 96: break;
        case 17: 
          { return symbol(sym.RBRACE);
          }
        case 97: break;
        case 28: 
          { return symbol(sym.NUMBER_NAME,		yytext());
          }
        case 98: break;
        case 47: 
          { token.append(yytext()); string.append("\\");
          }
        case 99: break;
        case 9: 
          { return symbol(sym.RELOP, yytext());
          }
        case 100: break;
        case 3: 
          { /* just skip */
          }
        case 101: break;
        case 44: 
          { token.append(yytext()); string.append("\r");
          }
        case 102: break;
        case 54: 
          { return symbol(sym.RBRACE_UNDERBAR_SLASH);
          }
        case 103: break;
        case 19: 
          { return symbol(sym.MINUS);
          }
        case 104: break;
        case 26: 
          { token.append(yytext()); string.append( yytext() );
          }
        case 105: break;
        case 49: 
          { token.append(yytext()); string.append("\f");
          }
        case 106: break;
        case 31: 
          { return symbol(sym.RULE, new Integer(yyline+1));
          }
        case 107: break;
        case 2: 
          { throw new Error("Illegal character <"+yytext()+"> at line "+(yyline+1));
          }
        case 108: break;
        case 27: 
          { token.append(yytext()); yybegin(YYINITIAL); return symbol(sym.STRING, string.toString(), token.toString(), startline, startcol);
          }
        case 109: break;
        case 40: 
          { return symbol(sym.RULENAMESEP);
          }
        case 110: break;
        case 55: 
          { return symbol(sym.RBRACE_UNDERBAR_AT);
          }
        case 111: break;
        case 46: 
          { token.append(yytext()); string.append("\"");
          }
        case 112: break;
        case 5: 
          { return symbol(sym.ATOM_NAME,			yytext());
          }
        case 113: break;
        case 13: 
          { return symbol(sym.COMMA);
          }
        case 114: break;
        case 22: 
          { return symbol(sym.TILDE);
          }
        case 115: break;
        case 1: 
          { 
          }
        case 116: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              throw new Error("EOF in string");
            }
            case 96: break;
            case QUOTED: {
              throw new Error("EOF in quoted name");
            }
            case 97: break;
            case COMMENT: {
              throw new Error("EOF in comment");
            }
            case 98: break;
            default:
              { return new java_cup.runtime.Symbol(sym.EOF); }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
