/* The following code was generated by JFlex 1.4_5 on 04/04/15 16:01 */

/**
	This is LMNtal Lex file.
*/

/* --------------------------Usercode Section------------------------ */
package compile.parser;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4_5
 * on 04/04/15 16:01 from the specification file
 * <tt>C:/Apps/eclipse/workspace/devel/src/compile/parser/lmntal.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int YY_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int QUOTED = 1;
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String yycmap_packed = 
    "\11\0\1\7\1\2\1\0\1\3\1\1\22\0\1\7\1\21\1\15"+
    "\1\14\1\42\1\30\1\0\1\16\1\32\1\33\1\27\1\13\1\31"+
    "\1\36\1\11\1\26\12\10\1\22\1\0\1\24\1\20\1\25\1\23"+
    "\1\43\2\4\1\4\1\4\1\12\25\4\1\44\1\17\1\45\1\40"+
    "\1\4\1\0\1\5\1\5\1\5\1\50\1\6\2\5\1\5\4\5"+
    "\1\46\1\5\1\47\2\5\1\5\1\5\1\5\6\5\1\34\1\37"+
    "\1\35\1\41\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] YY_ACTION = yy_unpack_YY_ACTION();

  private static final String YY_ACTION_packed0 =
    "\2\0\1\1\2\2\1\3\2\4\1\5\1\6\4\1"+
    "\1\7\1\1\1\10\3\7\1\11\1\12\1\2\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\4\3\30\3\0\1\31"+
    "\1\32\2\0\1\33\3\0\1\34\1\0\1\35\1\36"+
    "\1\0\1\37\1\40\1\41\1\42\1\4\1\43\1\44"+
    "\1\31\3\0\1\33\1\45\1\0\1\46\1\47\1\0";

  private static int [] yy_unpack_YY_ACTION() {
    int [] result = new int[73];
    int offset = 0;
    offset = yy_unpack_YY_ACTION(YY_ACTION_packed0, offset, result);
    return result;
  }

  private static int yy_unpack_YY_ACTION(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] yy_rowMap = yy_unpack_yy_rowMap();

  private static final String yy_rowMap_packed0 =
    "\0\0\0\51\0\122\0\173\0\122\0\244\0\315\0\366"+
    "\0\u011f\0\u0148\0\u0171\0\u019a\0\u01c3\0\u01ec\0\u0215\0\u023e"+
    "\0\u0267\0\122\0\u0290\0\u02b9\0\u02e2\0\u030b\0\u0334\0\122"+
    "\0\122\0\122\0\122\0\122\0\u035d\0\122\0\122\0\122"+
    "\0\122\0\122\0\u0386\0\122\0\u03af\0\122\0\u03d8\0\u0401"+
    "\0\u042a\0\u0453\0\u011f\0\u047c\0\122\0\u04a5\0\u019a\0\122"+
    "\0\u04ce\0\u04f7\0\u0520\0\122\0\u0549\0\122\0\122\0\u0572"+
    "\0\122\0\122\0\122\0\122\0\u059b\0\122\0\u05c4\0\u05ed"+
    "\0\u05ed\0\u0616\0\u063f\0\u019a\0\u0520\0\u0668\0\315\0\122"+
    "\0\u0691";

  private static int [] yy_unpack_yy_rowMap() {
    int [] result = new int[73];
    int offset = 0;
    offset = yy_unpack_yy_rowMap(yy_rowMap_packed0, offset, result);
    return result;
  }

  private static int yy_unpack_yy_rowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = ((int) packed.charAt(i++)) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] yytrans = yy_unpack_yytrans();

  private static final String yytrans_packed0 =
    "\1\3\1\4\2\5\1\6\2\7\1\5\1\10\1\11"+
    "\1\6\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\2\7\1\46\1\47"+
    "\43\46\1\50\3\46\53\0\1\5\52\0\3\6\1\0"+
    "\1\6\1\0\1\6\33\0\3\6\4\0\3\7\1\0"+
    "\1\7\1\51\1\7\33\0\3\7\6\0\1\52\1\0"+
    "\1\10\1\53\1\52\46\0\1\54\51\0\1\55\54\0"+
    "\1\56\33\0\1\57\2\0\12\57\1\60\1\57\1\61"+
    "\31\57\1\62\2\0\13\62\1\63\32\62\13\0\1\64"+
    "\4\0\1\22\47\0\1\65\1\22\1\0\1\65\1\0"+
    "\1\23\44\0\1\22\52\0\1\22\13\0\1\66\23\0"+
    "\1\22\50\0\1\22\6\0\1\23\41\0\1\67\14\0"+
    "\1\27\1\70\32\0\1\71\15\0\1\72\21\0\1\27"+
    "\1\4\2\5\45\27\11\0\1\73\103\0\1\74\10\0"+
    "\3\7\1\0\1\7\1\51\1\7\33\0\1\7\1\75"+
    "\1\7\2\0\1\46\113\0\1\76\10\0\2\77\1\0"+
    "\1\77\35\0\3\77\10\0\1\100\2\0\1\101\22\0"+
    "\1\101\20\0\1\52\1\0\1\54\1\0\1\52\36\0"+
    "\2\102\1\0\46\102\1\57\1\103\13\57\1\104\1\57"+
    "\1\61\31\57\1\62\2\0\13\62\1\105\32\62\16\0"+
    "\1\62\52\0\1\23\30\0\27\106\1\0\21\106\4\0"+
    "\3\7\1\0\1\7\1\51\1\7\33\0\2\7\1\107"+
    "\4\0\3\77\1\0\1\77\1\0\1\77\33\0\3\77"+
    "\10\0\1\100\55\0\1\110\35\0\1\57\46\0\27\106"+
    "\1\111\47\106\1\5\1\111\21\106";

  private static int [] yy_unpack_yytrans() {
    int [] result = new int[1722];
    int offset = 0;
    offset = yy_unpack_yytrans(yytrans_packed0, offset, result);
    return result;
  }

  private static int yy_unpack_yytrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int YY_UNKNOWN_ERROR = 0;
  private static final int YY_NO_MATCH = 1;
  private static final int YY_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] YY_ATTRIBUTE = yy_unpack_YY_ATTRIBUTE();

  private static final String YY_ATTRIBUTE_packed0 =
    "\2\0\1\11\1\1\1\11\14\1\1\11\5\1\5\11"+
    "\1\1\5\11\1\1\1\11\1\1\1\11\2\1\3\0"+
    "\1\1\1\11\2\0\1\11\3\0\1\11\1\0\2\11"+
    "\1\0\4\11\1\1\1\11\2\1\3\0\2\1\1\0"+
    "\1\1\1\11\1\0";

  private static int [] yy_unpack_YY_ATTRIBUTE() {
    int [] result = new int[73];
    int offset = 0;
    offset = yy_unpack_YY_ATTRIBUTE(YY_ATTRIBUTE_packed0, offset, result);
    return result;
  }

  private static int yy_unpack_YY_ATTRIBUTE(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	private final boolean _DEBUG = true;
	StringBuffer string = new StringBuffer();

    /* To create a new java_cup.runtime.Symbol with information about
       the current token, the token will have no value in this
       case. */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) throws java.io.IOException {
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    int [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_currentPos_l = yy_currentPos = yy_startRead = yy_markedPos_l;
  
      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {
    
          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action < 0 ? yy_action : YY_ACTION[yy_action]) {
        case 27: 
          { return symbol(sym.STRING, yytext()); }
        case 40: break;
        case 17: 
          { return symbol(sym.GUARD); }
        case 41: break;
        case 33: 
          { return symbol(sym.MINUS_DOT); }
        case 42: break;
        case 13: 
          { return symbol(sym.RPAREN); }
        case 43: break;
        case 39: 
          { return symbol(sym.CHAR_CODE_LITERAL, yytext()); }
        case 44: break;
        case 26: 
          { return symbol(sym.PLUS_DOT); }
        case 45: break;
        case 28: 
          { return symbol(sym.NEGATIVE); }
        case 46: break;
        case 25: 
          { return symbol(sym.NUMBER_NAME, yytext()); }
        case 47: break;
        case 34: 
          { string.setLength(0); yybegin(QUOTED); }
        case 48: break;
        case 18: 
          { return symbol(sym.HAT); }
        case 49: break;
        case 14: 
          { return symbol(sym.LBRACE); }
        case 50: break;
        case 1: 
          { throw new Error("Illegal character <"+yytext()+"> at line "+yyline); }
        case 51: break;
        case 22: 
          { return symbol(sym.LBRACKET); }
        case 52: break;
        case 20: 
          { return symbol(sym.PROCVAR); }
        case 53: break;
        case 9: 
          { return symbol(sym.SLASH); }
        case 54: break;
        case 21: 
          { return symbol(sym.RULEVAR); }
        case 55: break;
        case 6: 
          { return symbol(sym.PLUS); }
        case 56: break;
        case 38: 
          { return symbol(sym.MOD); }
        case 57: break;
        case 5: 
          { return symbol(sym.PERIOD); }
        case 58: break;
        case 10: 
          { return symbol(sym.ASTERISK); }
        case 59: break;
        case 36: 
          { return symbol(sym.PATHED_ATOM_NAME, yytext()); }
        case 60: break;
        case 23: 
          { return symbol(sym.RBRACKET); }
        case 61: break;
        case 8: 
          { return symbol(sym.COLON); }
        case 62: break;
        case 31: 
          { return symbol(sym.ASTERISK_DOT); }
        case 63: break;
        case 30: 
          { return symbol(sym.SLASH_DOT); }
        case 64: break;
        case 32: 
          { return symbol(sym.ASTERISK_ASTERISK); }
        case 65: break;
        case 37: 
          { return symbol(sym.SYMBOL_NAME, yytext()); }
        case 66: break;
        case 12: 
          { return symbol(sym.LPAREN); }
        case 67: break;
        case 15: 
          { return symbol(sym.RBRACE); }
        case 68: break;
        case 7: 
          { return symbol(sym.RELOP, yytext()); }
        case 69: break;
        case 2: 
          { /* just skip */ }
        case 70: break;
        case 16: 
          { return symbol(sym.MINUS); }
        case 71: break;
        case 35: 
          { yybegin(YYINITIAL); return symbol(sym.QUOTED_STRING, string.toString()); }
        case 72: break;
        case 3: 
          { return symbol(sym.LINK_NAME, yytext()); }
        case 73: break;
        case 29: 
          { return symbol(sym.RULE); }
        case 74: break;
        case 11: 
          { return symbol(sym.COMMA); }
        case 75: break;
        case 24: 
          { string.append( yytext() ); }
        case 76: break;
        case 19: 
          { return symbol(sym.TILDE); }
        case 77: break;
        case 4: 
          { return symbol(sym.ATOM_NAME, yytext()); }
        case 78: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
