
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 06 08:32:49 JST 2004
//----------------------------------------------------

package compile.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SLASH_DOT = 22;
  public static final int PLUS_DOT = 23;
  public static final int LBRACKET = 14;
  public static final int ASTERISK = 25;
  public static final int SLASH = 26;
  public static final int PERIOD = 10;
  public static final int LPAREN = 3;
  public static final int MINUS = 28;
  public static final int TILDE = 19;
  public static final int RBRACE_SLASH = 7;
  public static final int RPAREN = 4;
  public static final int RULE = 8;
  public static final int QUOTED_STRING = 29;
  public static final int MINUS_DOT = 24;
  public static final int NEGATIVE = 16;
  public static final int COMMA = 2;
  public static final int PROCVAR = 12;
  public static final int CHAR_CODE_LITERAL = 37;
  public static final int PLUS = 27;
  public static final int GUARD = 11;
  public static final int RELOP = 30;
  public static final int ASTERISK_DOT = 21;
  public static final int EOF = 0;
  public static final int RBRACKET = 15;
  public static final int error = 1;
  public static final int HAT = 18;
  public static final int RULEVAR = 13;
  public static final int MOD = 17;
  public static final int LINK_NAME = 32;
  public static final int COLON = 9;
  public static final int LBRACE = 5;
  public static final int SYMBOL_NAME = 34;
  public static final int PATHED_ATOM_NAME = 36;
  public static final int RBRACE = 6;
  public static final int NUMBER_NAME = 33;
  public static final int ATOM_NAME = 35;
  public static final int STRING = 31;
  public static final int ASTERISK_ASTERISK = 20;
}

