
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Wed Nov 09 23:55:51 JST 2005
//----------------------------------------------------

package compile.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SLASH_DOT = 24;
  public static final int PLUS_DOT = 25;
  public static final int LBRACKET = 16;
  public static final int ASTERISK = 27;
  public static final int SLASH = 28;
  public static final int PERIOD = 12;
  public static final int LPAREN = 3;
  public static final int MINUS = 30;
  public static final int RULENAMESEP = 31;
  public static final int TILDE = 21;
  public static final int RBRACE_SLASH = 7;
  public static final int RPAREN = 4;
  public static final int RULE = 10;
  public static final int QUOTED_STRING = 32;
  public static final int MINUS_DOT = 26;
  public static final int NEGATIVE = 18;
  public static final int COMMA = 2;
  public static final int PROCVAR = 14;
  public static final int CHAR_CODE_LITERAL = 40;
  public static final int PLUS = 29;
  public static final int GUARD = 13;
  public static final int RELOP = 33;
  public static final int ASTERISK_DOT = 23;
  public static final int EOF = 0;
  public static final int RBRACKET = 17;
  public static final int error = 1;
  public static final int HAT = 20;
  public static final int RULEVAR = 15;
  public static final int MOD = 19;
  public static final int LINK_NAME = 35;
  public static final int COLON = 11;
  public static final int LBRACE = 5;
  public static final int SYMBOL_NAME = 37;
  public static final int RBRACE_AT = 8;
  public static final int PATHED_ATOM_NAME = 39;
  public static final int RBRACE = 6;
  public static final int NUMBER_NAME = 36;
  public static final int RBRACE_SLASH_AT = 9;
  public static final int ATOM_NAME = 38;
  public static final int STRING = 34;
  public static final int ASTERISK_ASTERISK = 22;
}

