
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Mon Jun 26 21:15:30 JST 2006
//----------------------------------------------------

package compile.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SLASH_DOT = 28;
  public static final int PLUS_DOT = 29;
  public static final int LBRACKET = 20;
  public static final int ASTERISK = 31;
  public static final int SLASH = 32;
  public static final int RBRACE_UNDERBAR_SLASH_AT = 13;
  public static final int PERIOD = 16;
  public static final int LPAREN = 3;
  public static final int RULENAMESEP = 35;
  public static final int MINUS = 34;
  public static final int TILDE = 25;
  public static final int RBRACE_SLASH = 7;
  public static final int RPAREN = 4;
  public static final int RULE = 36;
  public static final int QUOTED_STRING = 37;
  public static final int MINUS_DOT = 30;
  public static final int NEGATIVE = 22;
  public static final int NUMBER_NAME16 = 42;
  public static final int COMMA = 2;
  public static final int PROCVAR = 18;
  public static final int CHAR_CODE_LITERAL = 46;
  public static final int PLUS = 33;
  public static final int RELOP = 38;
  public static final int GUARD = 17;
  public static final int ASTERISK_DOT = 27;
  public static final int EOF = 0;
  public static final int RBRACKET = 21;
  public static final int error = 1;
  public static final int HAT = 24;
  public static final int RULEVAR = 19;
  public static final int MOD = 23;
  public static final int LINK_NAME = 40;
  public static final int RBRACE_UNDERBAR_AT = 12;
  public static final int COLON = 15;
  public static final int LBRACE = 5;
  public static final int SYMBOL_NAME = 43;
  public static final int RBRACE_AT = 8;
  public static final int PATHED_ATOM_NAME = 45;
  public static final int RBRACE = 6;
  public static final int NUMBER_NAME = 41;
  public static final int RBRACE_SLASH_AT = 9;
  public static final int RBRACE_UNDERBAR_SLASH = 11;
  public static final int ATOM_NAME = 44;
  public static final int RBRACE_UNDERBAR = 10;
  public static final int STRING = 39;
  public static final int ASTERISK_ASTERISK = 26;
  public static final int RBRACE_ASTERISK = 14;
}

