print "// This file is auto generated by src/help_gen.pl\n";
print "// do not edit this file.\n";
print "package runtime;\n";
print "class Help {\n";
print "\tpublic static void show() {\n";
print "\t  System.out.println(\"\\nOptions:\\n\"\n";
while(<>) {
	next unless m|/// ([^\n\r]*)|;
	$v = $1; #chomp $v;
	print "\t\t".'+"';
	print "                " unless $v =~ /^\-/;
	print "    ".$v .'\n"'."\n";
}
print "\t  );\n";
print "\t}\n";
print "}\n";
