#!/usr/bin/perl

print <<END;
// This file is auto generated by src/help_gen.pl
// do not edit this file.
package runtime;
class Help {
	public static void show() {
		System.out.println(""
END

while(<>) {
	next unless m|/// ([^\n\r]*)|;
	$v = $1; #chomp $v;
	print <<END;
			+"@{[ $v =~ /^\-/ ? "" : "                " ]}    $v\\n"
END
}

print <<END;
		);
	}
}
END
