
  name: lmntal-compiler
  version: git # just for humans, typically '1.2+git' or '1.3.2'
  summary: LMNtal Compiler # 79 char long summary
  description: |
    This program is the de-facto standard compiler of 
    a hierarchical graph rewriting language, LMNtal.
    This outputs an intermediate instruction sequence
    which can be interpreted by SLIM, the de-facto
    standard runtime of LMNtal.

  base: core18

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  parts:
    lmntal-compiler:
      # See 'snapcraft plugins'
      plugin: ant
      source: .
      override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/lib/lmntal-compiler/lib
        mkdir -p $SNAPCRAFT_PART_INSTALL/lib/lmntal-compiler/bin
        mkdir -p $SNAPCRAFT_PART_INSTALL/lib/lmntal-compiler/classes
        cp -RT lib $SNAPCRAFT_PART_INSTALL/lib/lmntal-compiler/lib
        cp -RT bin $SNAPCRAFT_PART_INSTALL/lib/lmntal-compiler/bin
        cp -RT classes $SNAPCRAFT_PART_INSTALL/lib/lmntal-compiler/classes
      stage-packages: [openjdk-8-jre]
  
  apps:
    lmntal-compiler:
      command: lib/lmntal-compiler/bin/lmntal
